tsts

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -110,7 +110,6 @@ ret["packages"] = sys.stdin.read().splitlines()
 c_json = dict(json.load(open("composer.json"))) # wrap in dict() to prevent simple errors with {} vs []
 ret["json"] = {k: c_json.get(k, None) for k in ["minimum-stability", "prefer-stable"]}
 ret["json"]["platform"] = {k: dict(c_json.get("require", {})).get(k, None) for k in ["php", "hhvm"]} # wrap in dict() to prevent simple errors with {} vs []
-
 try:
     c_lock = json.load(open("composer.lock"))
     ret["lock"] = {k: c_lock.get(k, None) for k in ["minimum-stability", "prefer-stable", "stability-flags"]}
@@ -120,7 +119,7 @@ except IOError:
 print json.dumps(ret)
 ' 2> /dev/null) || error "Couldn't parse composer.lock; it must be valid JSON.
 Run 'composer update' to have it re-generated by Composer."
-    solver_result="SOLVER_RESULT"
+    solver_result=$(echo -n "$solver_payload") || error "Failed to resolve runtime requirements.
 If the issue persists, please contact support."
     while IFS="|" read runtime_name runtime_source runtime_constraint runtime_result; do
         if [[ $runtime_result ]]; then
@@ -263,13 +262,22 @@ fi
 status "Installing dependencies..."
 
 # check if we should use a composer.phar version bundled with the project
-
+if [[ -f "composer.phar" ]]; then
+    [[ -x "composer.phar" ]] || error "File '/composer.phar' isn't executable; please 'chmod +x'!"
+    $engine_r 'new Phar("composer.phar");' &> /dev/null || error "File '/composer.phar' is not a valid PHAR archive!"
+    composer() {
+        $engine composer.phar "$@"
+    }
+    export -f composer
+    composer --version 2>&1 | grep "^Composer version" > /dev/null || error "File '/composer.phar' is not a Composer executable!"
+    notice_inline "Using '/composer.phar' to install dependencies."
+else
     curl --silent --location "$S3_URL/composer.tar.gz" | tar xz -C $BUILD_DIR/.heroku/php
     composer() {
         $engine `which composer` "$@"
     }
     export -f composer
-
+fi
 # echo composer version for info purposes
 # tail to get rid of outdated version warnings (Composer sends those to STDOUT instead of STDERR)
 composer --version 2> /dev/null | tail -n 1 | indent
@@ -299,7 +307,12 @@ if [[ -n "$COMPOSER_GITHUB_OAUTH_TOKEN" ]]; then
 else
     # don't forget to remove any stored key if it's gone from the env
     composer config -g --unset github-oauth.github.com &> /dev/null # redirect outdated version warnings (Composer sends those to STDOUT instead of STDERR)
-
+    if curl --silent https://api.github.com/rate_limit | python -c 'import sys, json; sys.exit((json.load(sys.stdin)["resources"]["core"]["remaining"] > 0))'; then # yes, check > 0, not < 1 - exit status of 0 will trigger the if
+        notice "You've reached the GitHub API's request rate limit.
+Composer will try and fall back to slower downloads from source.
+It's strongly recommended you use a custom OAuth token; see
+http://devcenter.heroku.com/articles/php-support#custom-github-oauth-tokens"
+    fi
 fi
 # no need for the token to stay around in the env
 unset COMPOSER_GITHUB_OAUTH_TOKEN
@@ -310,7 +323,10 @@ composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction |
 composer show --installed heroku/heroku-buildpack-php &> /dev/null && error "Your composer.json requires 'heroku/heroku-buildpack-php'.
 This package may only be used as a dependency in 'require-dev'!"
 
-
+if cat composer.json | python -c 'import sys,json; sys.exit("compile" not in json.load(sys.stdin).get("scripts", {}));'; then
+    status "Running 'composer compile'..."
+    composer run-script --no-dev --no-interaction compile | indent
+fi
 
 status "Preparing runtime environment..."
 
